### ISSUE TITLE
General help

### ISSUE THREAD

**Issue by Echo-Wxlf** [equdevel/SnowRunner_mod_installer#1]
I've been trying to get this to work and looking at your code but it just refuses to work, every time I solve one problem another pops up, could you offer some help please?

**Comment by equdevel** [comment]
> I've been trying to get this to work and looking at your code but it just refuses to work, every time I solve one problem another pops up, could you offer some help please?

How can I help if you haven't written what exactly doesn't work?

**Comment by mardendiller** [comment]
Hey bro, I tried to use this mod installer for v24 SnowRunner, RUNE version on FitGirl repack. The mods install normally, appear in the mod manager but the game says they can't be activated. Any ideas on how to solve it?

**Comment by equdevel** [comment]
> Hey bro, I tried to use this mod installer for v24 SnowRunner, RUNE version on FitGirl repack. The mods install normally, appear in the mod manager but the game says they can't be activated. Any ideas on how to solve it?

Hi! I haven't tested installer on v24 yet.

**Comment by mardendiller** [comment]
> > Hey bro, I tried to use this mod installer for v24 SnowRunner, RUNE version on FitGirl repack. The mods install normally, appear in the mod manager but the game says they can't be activated. Any ideas on how to solve it?
> 
> Hi! I haven't tested installer on v24 yet.

Hello! I asked for the help of a friend of mine who can read and write in Phyton hahahaha we managed to make it work like a charm on v24, just install all the modules on Python (guess it's a basic move, maybe). Congrats on the amazing job and thank you, I've been burning my brain for a week or so looking for a solution.

**Comment by equdevel** [comment]
> > > Hey bro, I tried to use this mod installer for v24 SnowRunner, RUNE version on FitGirl repack. The mods install normally, appear in the mod manager but the game says they can't be activated. Any ideas on how to solve it?
> > 
> > 
> > Hi! I haven't tested installer on v24 yet.
> 
> Hello! I asked for the help of a friend of mine who can read and write in Phyton hahahaha we managed to make it work like a charm on v24, just install all the modules on Python (guess it's a basic move, maybe). Congrats on the amazing job and thank you, I've been burning my brain for a week or so looking for a solution.

Also you can download exe-file from Releases. It includes all required python modules and does not require python to be installed.

**Comment by Torrenthor** [comment]
Any fix for Error (401) mod dependency Error?
https://ibb.co/1sC31cy
One example of mods throwing the error.
https://mod.io/g/snowrunner/m/ford-clt9000-truck-norris

**Comment by equdevel** [comment]
> Any fix for Error (401) mod dependency Error? https://ibb.co/1sC31cy One example of mods throwing the error. https://mod.io/g/snowrunner/m/ford-clt9000-truck-norris

The installer only downloads and unpacks mods from mod.io. Downloading mods is not available in the game interface (for unlicensed version of game). You must block SnowRunner outgoing traffic in Windows firewall.

**Comment by Torrenthor** [comment]
If you're activating the mods through the mod browser, blocking outbound and inbound traffic in the firewall will still result in an error, this time code 10001. The problem seems to be fixed by manually adding the mod to user_profile.cfg, and doing so would not cause any more errors.

**Comment by KapitanSuchar** [comment]
> If you're activating the mods through the mod browser, blocking outbound and inbound traffic in the firewall will still result in an error, this time code 10001. The problem seems to be fixed by manually adding the mod to user_profile.cfg, and doing so would not cause any more errors.

Can you show an example how to add mod manually?

Edit: Found it in some video on toutube, leaving here for others:
{"UserProfile":{"lastAgreement":1,"areModsPermitted":1,"modFilter":{"user0":{"SslType":"ModBrowserConfigData","SslValue":{"sortIsAsc":false,"isSubscriptionsMode":true,"isConsoleApprovedMode":false,"tags":[],"isConsoleForbiddenMode":false,"sortField":"popular","isEnabledMode":true}}},"modStateList":[{"modState":true,"modId":956072},{"modState":true,"modId":991967},{"modState":true,"modId":2541608},{"modState":true,"modId":2840052},{"modState":true,"modId":3212858}],"gdprAccept":true,"modTags":{"SslSubtype":["ModBrowserFilterTagGroup"],"SslValue":[],"SslType":"array"},"gdprSeen":true,"lastSaves":1,"saveSlot":2},"cfg_version":1} 

After changing remember to switch file to read only

**Comment by Sha9811** [comment]
Thank you for your time and your work. I appreciate it!
Could I please ask for your assistance with this issue? 

When I try to run the executable (edited `.env` file, checked token, both directories correct)
I get "CONNECTION TO mod.io FAILED: status code_code=403"

these are the things I have done in hopes of mitigating this issue. 
- running it as admin
- excluding mod_installer from defender/firewall
- specifically allowing inbound and outbound connections
- running it with defender and firewall disabled
- checked and validated mod.io token and access to api

**Comment by Sha9811** [comment]
> Thank you for your time and your work. I appreciate it! Could I please ask for your assistance with this issue?
> 
> When I try to run the executable (edited `.env` file, checked token, both directories correct) I get "CONNECTION TO mod.io FAILED: status code_code=403"
> 
> these are the things I have done in hopes of mitigating this issue.
> 
>     * running it as admin
> 
>     * excluding mod_installer from defender/firewall
> 
>     * specifically allowing inbound and outbound connections
> 
>     * running it with defender and firewall disabled
> 
>     * checked and validated mod.io token and access to api

did some researching and I think its mod.io blocking the request. If I had a better understanding of python, I would try to do it manually. 
Is there any way of mitigating this issue?

**Comment by equdevel** [comment]
> > Thank you for your time and your work. I appreciate it! Could I please ask for your assistance with this issue?
> > When I try to run the executable (edited `.env` file, checked token, both directories correct) I get "CONNECTION TO mod.io FAILED: status code_code=403"
> > these are the things I have done in hopes of mitigating this issue.
> > ```
> > * running it as admin
> > 
> > * excluding mod_installer from defender/firewall
> > 
> > * specifically allowing inbound and outbound connections
> > 
> > * running it with defender and firewall disabled
> > 
> > * checked and validated mod.io token and access to api
> > ```
> 
> did some researching and I think its mod.io blocking the request. If I had a better understanding of python, I would try to do it manually. Is there any way of mitigating this issue?

FIXED
