### ISSUE TITLE
Where do I find usage documentation? 

### ISSUE THREAD

**Issue by mpjbay** [equdevel/SnowRunner_mod_installer#2]
Thank you for putting this together. 

I downloaded the exe. Not sure to use it. Is there documentation or a video somewhere that how to install mods using your program? 

Thanks in advance.

**Comment by equdevel** [comment]
Read the [README](https://github.com/equdevel/SnowRunner_mod_installer/blob/master/README.md) please.

**Comment by equdevel** [comment]
> Thank you for putting this together.
> 
> I downloaded the exe. Not sure to use it. Is there documentation or a video somewhere that how to install mods using your program?
> 
> Thanks in advance.

Read the [README](https://github.com/equdevel/SnowRunner_mod_installer/blob/master/README.md) please.

**Comment by mpjbay** [comment]
Thank you. not sure how I missed that.

Does this work on pirated copies? In game "Mod Browser" does not open for me.

**Comment by equdevel** [comment]
> Thank you. not sure how I missed that.

I wrote a README yesterday after your question )



> Does this work on pirated copies? In game "Mod Browser" does not open for me.

Yes, this tool was written precisely for this purpose. Have you completed step 9? (go to "Load", exit back - needed to activate the "View modifications" item). If everything is done exactly according to the instructions, then everything should work. Tested on EGS and Steam versions.

**Comment by mpjbay** [comment]
OK, I ran through the instructions again. 

Step 4: I had to manually change the file extension from .cfg to .dat. I did not see this in the instructions but figured it was what needed to be done since we are replacing the user-profile file. Once I made the extension change the program ran which was good. Also, I do not have "storage/0/" I have "storage/" which is where user_profile lives so I used the path on my machine.

EGS profile: C:/Users/USER_NAME/Documents/My Games/SnowRunner/base/storage/0/user_profile.dat

I ran "mod_installer.exe". The mods downloaded into the correct directory and unpacked.

Step 9 does not work as expected so I am stuck there: **When I run the game I do not see the "Load" option on the main menu screen.** 

Here is the user_profile.dat output once mod_installer.exe is run in case it is helpful.

{
    "UserProfile": {
        "areModsPermitted": 1,
        "lastSaves": 1,
        "gdprSeen": true,
        "gdprAccept": true,
        "lastAgreement": 1,
        "modDependencies": {
            "SslType": "ModDependencies",
            "SslValue": {
                "dependencies": {
                    "118499": [],
                    "126080": [],
                    "142819": [],
                    "151845": [],
                    "157932": [],
                    "163143": [],
                    "164561": [],
                    "177767": [],
                    "181936": [],
                    "464151": [],
                    "515350": [],
                    "670268": [],
                    "758643": [],
                    "1096632": [],
                    "1167137": [],
                    "1419761": [],
                    "3084125": []
                }
            }
        },
        "modFilter": {
            "user0": {
                "SslType": "ModBrowserConfigData",
                "SslValue": {
                    "tags": [],
                    "sortField": "popular",
                    "isSubscriptionsMode": false,
                    "isEnabledMode": false,
                    "isConsoleApprovedMode": false,
                    "isConsoleForbiddenMode": false,
                    "sortIsAsc": false
                }
            }
        },
        "modTags": {
            "SslSubtype": [
                "ModBrowserFilterTagGroup"
            ],
            "SslType": "array",
            "SslValue": []
        }
    },
    "cfg_version": 1
}

**Comment by equdevel** [comment]
> Step 9 does not work as expected so I am stuck there: **When I run the game I do not see the "Load" option on the main menu screen.**

I don't know what this menu item looks like in English, because my game is in Russian. This menu item is used to load game saves. In English there should be something like "Load game" or "Load game save".

**Comment by equdevel** [comment]
> Here is the user_profile.dat output once mod_installer.exe is run in case it is helpful.

Looks OK

**Comment by equdevel** [comment]
> I had to manually change the file extension from .cfg to .dat. I did not see this in the instructions but figured it was what needed to be done since we are replacing the user-profile file.

This is the difference between Steam and EGS. Save files also have different extensions.

**Comment by equdevel** [comment]
> Also, I do not have "storage/0/" I have "storage/" which is where user_profile lives so I used the path on my machine.

The paths may differ depending on the type of pirated copy. I don't know all the variants.

**Comment by mpjbay** [comment]
> "I don't know what this menu item looks like in English, because my game is in Russian. This menu item is used to load game saves. In English there should be something like "Load game" or "Load game save"."

Thank you for your replies. I've always wanted to visit Russia. 

OK, I did open the option to load saved games then exited back to the main menu I do not see an option to view installed mods.

**Comment by equdevel** [comment]
> OK, I did open the option to load saved games then exited back to the main menu I do not see an option to view installed mods.

Take a screenshot please.

**Comment by mpjbay** [comment]
> Take a screenshot please.

Here you go. When I exit back from the "LOAD GAME" screen, the main menu is unchanged. 

![menu](https://github.com/equdevel/SnowRunner_mod_installer/assets/24557002/c4e489e5-16af-4909-a09f-2bac44d9c147)


![loadgame](https://github.com/equdevel/SnowRunner_mod_installer/assets/24557002/d56395e3-b892-4ad3-93c1-c1f24788c023)

**Comment by equdevel** [comment]
"MOD BROWSER" - this is what you need. Sometimes this menu item is available immediately, but usually after entering and exiting "Load". Go to "MOD BROWSER" and enable the mods you need, then load the saved game, the mods will become available in the store.
In the second screenshot there is a message "MODS OFFLINE. Unable to reach mod.io.", do not pay attention to it, that's how it should be.

**Comment by mpjbay** [comment]
That is what I thought however when I try to open "Mod Browser" I get 

![ModB](https://github.com/equdevel/SnowRunner_mod_installer/assets/24557002/fc063c65-e13b-4a9c-8279-577af6dd6b49)

**Comment by equdevel** [comment]
Perhaps my installer is not compatible with your pirated copy. I only tested two main pirated builds. Try downloading another build.

**Comment by equdevel** [comment]
On the screenshots I see the RUNE build. I haven't tested it. Try downloading the CODEX build (Steam version).

**Comment by mpjbay** [comment]
Will do. 

Do you have a link to a current CODEX version? The private tracker I typically use doesn't have a current CODEX game version, only an older version.

**Comment by equdevel** [comment]
It is unlikely that you will be satisfied with the Russian version. Try googling.

**Comment by mpjbay** [comment]
I do not use Google but I will look around. I thought CODEX stopped cracking a couple years ago. I looked around and cannot find the new version of Snowrunner from CODEX, only an old version from a couple years ago. The new version is "Lights Camera".  I suppose this is why I am using a RUNE version.

**Comment by equdevel** [comment]
> I thought CODEX stopped cracking a couple years ago. I looked around and cannot find the new version of Snowrunner from CODEX, only an old version from a couple years ago.

I use build 26.2 with CODEX crack.

**Comment by mpjbay** [comment]
Does your copy have ENG and RUSSIAN? I wonder if the crack will work with the RUNE copy? What site do you use?

**Comment by equdevel** [comment]
Write your email.

**Comment by mpjbay** [comment]
m@matttani.com
