### ISSUE TITLE
Mods are moved to cache if I have 100+ mods

### ISSUE THREAD

**Issue by rexizam** [equdevel/SnowRunner_mod_installer#6]
If I have over 100 mod subscriptions the mod installer moves the excess mods to the cache folder. Then I have to manually move them back to mods directory and edit "modStateList" and "modDependencies" in user_profile.cfg to enable them.

I checked my mod data in Postman and I noticed that some mods have "null" version or "Rpk" so that could be causing the issue perhaps ?

How to reproduce:

1. Subscribe to 101 mods on mod.io
2. Run mod_installer.exe
3. The installer should move 1 mod to which I'm subscribed to cache folder and disable it

**Comment by equdevel** [comment]
Does the installer display the message "Moving to cache unsubscribed mod with id=" ?

**Comment by equdevel** [comment]
> 3\. The installer should move 1 mod to which I'm subscribed to cache folder and disable it

Does the installer display the message "Moving to cache unsubscribed mod with id=" ?

**Comment by rexizam** [comment]
Yes it does. In my case I have 145 subscriptions and when I run installer it takes 45 mods out of the mods folder.

<img width="675" alt="Untitled" src="https://github.com/equdevel/SnowRunner_mod_installer/assets/50618325/5301ee40-a080-4c97-857f-535dff8fed3d">

**Comment by equdevel** [comment]
This is because there is a server response limit of 100 mods subscriptions per request.
![request_102-mods](https://github.com/equdevel/SnowRunner_mod_installer/assets/53164014/d3bebe4e-3159-47f4-aa40-483ad9d9b482)

**Comment by equdevel** [comment]
The limit is unlocked now.
