### ISSUE TITLE
VirusTotal and HybridAnalysis flags for the installer

### ISSUE THREAD

**Issue by Sha9811** [equdevel/SnowRunner_mod_installer#7]
First and foremost, thanks to the developer for your time in creating and maintaining this tool for the rest of us to use. 

### **For the other people who may be alarmed, please read this first.** 
> - **Understanding VirusTotal and HybridAnalysis Flags:** These services often flag executables with false positives based on certain behaviors typical of benign software as well. These results are not conclusive. 
> - **Flagged Installer:** Both VirusTotal and HybridAnalysis have flagged the installer. If you are concerned about the potential risks, please consider reviewing the source code yourself or avoid using the installer.
> - **Source Code Review:** For those who are capable, I encourage you to review the source code directly. If you determine the source code is safe, you might consider running the source code directly or compiling it yourself. 
> - **Developer’s Efforts:** It’s important to recognize that the author has invested personal time into developing and maintaining this tool free of charge for other people to use.

As for the author, here is the link for vt and hybridanalysis
[VirusTotal Results](https://www.virustotal.com/gui/file/258c3b26085ee5801855c619f8b6582650c4d244c87bc8fdc2d556804d3f3236)
`https://www.virustotal.com/gui/file/258c3b26085ee5801855c619f8b6582650c4d244c87bc8fdc2d556804d3f3236`
[HybridAnalysis Results](https://www.hybrid-analysis.com/sample/258c3b26085ee5801855c619f8b6582650c4d244c87bc8fdc2d556804d3f3236)
`https://www.hybrid-analysis.com/sample/258c3b26085ee5801855c619f8b6582650c4d244c87bc8fdc2d556804d3f3236`

To the best of my knowledge and speaking strictly in terms of the source code itself, the source code looks clean and does what it's expected to do. I haven't done any de-compiling of the installer yet, but my suspicions for this are

- HTTP requests using bearer tokens for API requests
- file operations method. Specifically, this script does downloading, creating, deleting, and modifying files and directories. Therefore, Trojan flag on heuristics. 
- using environment variables. This tends to drive heuristics engines nuts when they involve paths and network settings. 
- has external libraries `requests` and `tqdm` as it's dependency. 

in my opinion, as long as the executable has not been tampered with post-compilation, its just mundane things like code behavior, different compiler settings that triggered this. 
I just wanted to bring this to your attention, and I look forward to any further insights or clarifications you might provide.
Thanks for your time!

**Comment by equdevel** [comment]
I "compiled" the script into an executable using pyinstaller just for convenience, so that the user does not have to download and install Python. Doubters can install Python and run the script directly.
