### ISSUE TITLE
Failed to connect to mod io

### ISSUE THREAD

**Issue by SnakeSol** [equdevel/SnowRunner_mod_installer#9]
After following all steps of the readme, I'm unable to activate only some of my mods. I unsuscribed all of my mods, cleared cache, resuscribed, re installed like 3 or 4 times, but always the same problem: unable to activate the mod, please verify connection, errror 10001

![image](https://github.com/equdevel/SnowRunner_mod_installer/assets/73792210/9c3c3a20-8e81-4e08-a1fc-4d2510d2358f)

**Comment by HorkayZolee** [comment]
Hi! Same here. It worked fine for me until now, but today I wanted to activate a mod and the 401 error occurred. Version 1.6.6

**Comment by HorkayZolee** [comment]
Today as a test deleted the existing user_profile.cfg and used the downloaded "clean" file. Then started the mod installer. It now updates user_profile.cfg. Now mods can be turned on/off ingame. For some reason it doesn't overwrite the user_profile.cfg file saved by the game.

**Comment by equdevel** [comment]
> Today as a test deleted the existing user_profile.cfg and used the downloaded "clean" file. Then started the mod installer. It now updates user_profile.cfg. Now mods can be turned on/off ingame. For some reason it doesn't overwrite the user_profile.cfg file saved by the game.

user_profile.cfg from the archive is a prerequisite for the installer to work
